[keys]
telegram = "TELEGRAM_API_KEY"
gemini = "GEMINI_API_KEY"

[bot]
prompt = "You are Benebott, you are in a group chat and the messages will come in the format of '[username] message'"
max_history = 10
mock_chance = 0.005
